In [1]:
import os, sys
sys.path.insert(1, "/".join(os.path.abspath('').split("/")[:-1]))

import torch
from transformer.layers.multi_head_attention.attention_mechanism import AttentionMechanism
from transformer.layers.multi_head_attention.attention_mechanism.attn_params import CosformerParams, PerformerParams, VanillaParams


/Users/cezarygolecki/projects/magisterka/.venv/lib/python3.11/site-packages/rotary_embedding_torch/rotary_embedding_torch.py:35: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)
/Users/cezarygolecki/projects/magisterka/.venv/lib/python3.11/site-packages/rotary_embedding_torch/rotary_embedding_torch.py:262: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled = False)


# Vanilla

In [10]:
batch_size = 2
seq_len = 5
embed_dim = 6
device = "cpu"
x = torch.rand((batch_size, seq_len, embed_dim)).to(device)
v = torch.rand((batch_size, seq_len, embed_dim)).to(device)

attn = AttentionMechanism(embed_dim, 2, VanillaParams(), False, device)
print(attn(x,x,x, causal=True))

tensor([[[0.5657, 0.9102, 0.4936, 0.4829, 0.8961, 0.7027],
         [0.3888, 0.6483, 0.7919, 0.5930, 0.6692, 0.8222],
         [0.5063, 0.5966, 0.6915, 0.1719, 0.1601, 0.7999],
         [0.3149, 0.1427, 0.8747, 0.5326, 0.1205, 0.7668],
         [0.5580, 0.1022, 0.6013, 0.5190, 0.3250, 0.5759]],

        [[0.9509, 0.2620, 0.6980, 0.8866, 0.2526, 0.7136],
         [0.7622, 0.4612, 0.4851, 0.7294, 0.4967, 0.4696],
         [0.7167, 0.5124, 0.4571, 0.0791, 0.8449, 0.8229],
         [0.0682, 0.7522, 0.7331, 0.2848, 0.5429, 0.5549],
         [0.2151, 0.6011, 0.4759, 0.2385, 0.5742, 0.5680]]])


# Cosformer

In [3]:
batch_size = 2
seq_len = 5
embed_dim = 6
device = "cpu"
x = torch.rand((batch_size, seq_len, embed_dim)).to(device)
v = torch.rand((batch_size, seq_len, embed_dim)).to(device)

attn = AttentionMechanism(embed_dim, 2, CosformerParams(), False, device)
print(attn(x,x,x, causal=True))

tensor([[[0.2991, 0.9926, 0.3933, 0.3136, 0.1052, 0.3166],
         [0.8526, 0.9559, 0.4633, 0.6674, 0.5996, 0.2802],
         [1.0752, 1.5707, 0.8684, 0.6495, 0.8557, 0.4554],
         [1.7370, 1.3269, 1.2396, 0.9752, 1.4806, 0.9087],
         [2.3836, 1.9958, 2.1230, 1.4396, 1.9670, 1.0837]],

        [[0.3712, 0.1316, 0.0452, 0.5839, 0.1278, 0.3976],
         [1.0730, 0.4279, 0.9435, 0.6794, 0.0643, 0.6653],
         [1.7908, 1.0752, 1.8308, 0.9476, 0.2954, 1.0438],
         [2.1132, 1.3679, 2.8403, 1.5904, 0.9394, 1.6625],
         [1.9424, 1.1334, 1.0542, 1.4976, 0.9985, 1.3352]]])


# Performer

In [4]:
batch_size = 2
seq_len = 5
embed_dim = 4
device = "cpu"

x = torch.rand((batch_size, seq_len, embed_dim)).to(device)
v = torch.rand((batch_size,  seq_len, embed_dim)).to(device)

attn = AttentionMechanism(embed_dim, 2, PerformerParams(),False, device)
attn(x,x,v, causal=True)

tensor([[[0.2452, 0.3107, 0.0795, 0.3327],
         [0.7542, 0.3549, 0.1530, 0.4360],
         [0.8820, 0.7193, 0.1883, 0.5667],
         [1.7823, 1.2945, 0.6118, 1.0059],
         [1.6973, 1.8332, 0.7441, 1.2979]],

        [[0.8837, 0.2715, 0.0040, 0.1325],
         [1.2079, 0.2971, 0.2609, 0.3057],
         [2.0842, 0.4372, 0.4336, 0.7278],
         [1.6103, 0.8445, 0.6614, 0.8883],
         [1.7393, 1.4167, 0.8956, 1.3014]]])